#define _POSIX_C_SOURCE 200809L
#include "http_server.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Detailed, beginner-friendly C function reference
// Focused on network programming and practical usage

void handle_glossary(const HttpRequest *request, HttpResponse *response)
{
    (void)request;

    size_t total_size = 90000;
    char *html = malloc(total_size);
    if (!html)
    {
        response->status_code = 500;
        strcpy(response->content_type, "text/plain");
        response->body = strdup("Memory allocation failed");
        response->body_length = strlen(response->body);
        return;
    }

    // Build comprehensive HTML with detailed explanations
    snprintf(html, total_size,
             "<!DOCTYPE html><html><head><title>C Functions Guide</title>"
             "<style>"
             "body{font-family:monospace;max-width:1400px;margin:0 auto;padding:20px;background:#0a0a0a;color:#00ff00;line-height:1.7;}"
             "h1{border-bottom:3px solid #00ff00;padding-bottom:15px;font-size:32px;}"
             ".search{position:sticky;top:0;background:#0a0a0a;padding:20px 0;z-index:100;}"
             "#s{width:100%%;padding:15px;background:#1a1a1a;border:2px solid #00ff00;color:#00ff00;font-size:18px;}"
             ".cat{margin:40px 0;}"
             ".cat h2{color:#00aaff;border-bottom:2px solid #00aaff;padding:10px 0;font-size:26px;}"
             ".entry{background:#1a1a1a;padding:25px;margin:20px 0;border-left:5px solid #00ff00;}"
             ".entry h3{color:#ffaa00;font-size:22px;margin:0 0 15px;}"
             ".label{color:#00aaff;font-weight:bold;display:block;margin:15px 0 8px;font-size:16px;}"
             "pre{background:#000;padding:15px;margin:12px 0;overflow-x:auto;border-left:4px solid #00aaff;}"
             ".tip{background:#0a2a0a;padding:12px;margin:12px 0;border-left:4px solid #44ff44;color:#88ff88;}"
             ".warn{background:#2a0a0a;padding:12px;margin:12px 0;border-left:4px solid #ff4444;color:#ff8888;}"
             "code{background:#2a2a2a;padding:3px 7px;color:#ffaa00;}"
             "ul{margin:10px 0 10px 25px;}li{margin:8px 0;}"
             "a{color:#00ff00;text-decoration:none;}a:hover{color:#00aaff;}"
             "</style></head><body>"

             "<h1>📚 C Functions Reference - Beginner Friendly</h1>"
             "<p style='font-size:18px;color:#00aaff;'>Detailed explanations of every function in this server. "
             "No prior C knowledge required!</p>"

             "<div class='search'><input id='s' placeholder='Search: socket, malloc, send, printf...' autofocus>"
             "<div id='c' style='color:#00aaff;margin-top:8px;'></div></div>"

             // Memory Management
             "<div class='cat'><h2>🧠 Memory Functions</h2>"

             "<div class='entry'><h3>malloc(size_t size)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Allocates memory on the heap (dynamic memory that lasts until you free it). "
             "Think of it like renting storage space.</p>"
             "<span class='label'>Why you need it:</span>"
             "<p>When you don't know the size needed at compile time - like reading a file of unknown size, "
             "building HTTP responses, or storing user input.</p>"
             "<span class='label'>Example:</span>"
             "<pre>// Allocate space for 100 integers\n"
             "int *arr = malloc(100 * sizeof(int));\n"
             "if (arr == NULL) {\n"
             "    printf(\"Out of memory!\\n\");\n"
             "    return -1;\n"
             "}\n"
             "arr[0] = 42;  // Use it\n"
             "free(arr);    // MUST free!</pre>"
             "<div class='tip'>💡 Always check for NULL and always free() when done</div>"
             "<div class='warn'>⚠️ Memory leaks happen when you malloc without free</div></div>"

             "<div class='entry'><h3>free(void *ptr)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Releases memory back to the system. Like returning rented storage.</p>"
             "<span class='label'>Example:</span>"
             "<pre>char *msg = malloc(100);\n"
             "strcpy(msg, \"Hello\");\n"
             "free(msg);\n"
             "msg = NULL;  // Good practice</pre></div>"

             "<div class='entry'><h3>memset(void *ptr, int value, size_t num)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Fills memory with a byte value. Usually used to zero-out (clear) memory.</p>"
             "<span class='label'>Why:</span>"
             "<p>New memory contains garbage. Clear it before use!</p>"
             "<span class='label'>Example:</span>"
             "<pre>char buffer[100];\n"
             "memset(buffer, 0, sizeof(buffer));  // All zeros\n"
             "\n"
             "struct sockaddr_in addr;\n"
             "memset(&addr, 0, sizeof(addr));  // Clear struct</pre></div>"

             // String Functions
             "</div><div class='cat'><h2>📝 String Functions</h2>"

             "<div class='entry'><h3>printf(const char *format, ...)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Prints formatted text to screen. Your main tool for showing information!</p>"
             "<span class='label'>Format codes:</span>"
             "<ul><li>%%d - integer</li><li>%%s - string</li><li>%%c - character</li>"
             "<li>%%f - float</li><li>%%p - pointer</li><li>%%zu - size_t</li></ul>"
             "<span class='label'>Example:</span>"
             "<pre>printf(\"Server on port %%d\\n\", 8080);\n"
             "printf(\"IP: %%s, Port: %%d\\n\", \"127.0.0.1\", 8080);</pre>"
             "<div class='tip'>💡 Use printf for debugging - see what variables contain!</div></div>"

             "<div class='entry'><h3>snprintf(char *str, size_t size, ...)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Like printf but writes to string buffer SAFELY (won't overflow).</p>"
             "<span class='label'>Why it's better than sprintf:</span>"
             "<p>Takes a size parameter - prevents buffer overflow vulnerabilities!</p>"
             "<span class='label'>Example:</span>"
             "<pre>char buf[100];\n"
             "snprintf(buf, sizeof(buf), \"Port: %%d\", 8080);\n"
             "\n"
             "// Building HTTP response\n"
             "snprintf(response, sizeof(response),\n"
             "    \"HTTP/1.1 200 OK\\r\\n\"\n"
             "    \"Content-Length: %%zu\\r\\n\\r\\n\",\n"
             "    body_len);</pre>"
             "<div class='warn'>⚠️ Never use sprintf - always use snprintf!</div></div>"

             "<div class='entry'><h3>strlen(const char *str)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Returns string length (not including \\0 terminator).</p>"
             "<span class='label'>Example:</span>"
             "<pre>char *msg = \"Hello\";\n"
             "size_t len = strlen(msg);  // len = 5\n"
             "\n"
             "// When sending data\n"
             "send(sock, buffer, strlen(buffer), 0);</pre>"
             "<div class='tip'>💡 \"Hello\" has strlen=5 but needs 6 bytes (5 + \\0)</div></div>"

             "<div class='entry'><h3>strcmp(const char *s1, const char *s2)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Compares two strings. CANNOT use == for strings in C!</p>"
             "<span class='label'>Returns:</span>"
             "<ul><li>0 = strings are EQUAL</li><li>&lt;0 = s1 before s2</li><li>&gt;0 = s1 after s2</li></ul>"
             "<span class='label'>Example:</span>"
             "<pre>// WRONG!\n"
             "if (str1 == str2) { }  // Compares pointers, not content\n"
             "\n"
             "// CORRECT\n"
             "if (strcmp(str1, str2) == 0) {\n"
             "    printf(\"Equal!\\n\");\n"
             "}\n"
             "\n"
             "// Routing\n"
             "if (strcmp(path, \"/api\") == 0) {\n"
             "    handle_api();\n"
             "}</pre>"
             "<div class='warn'>⚠️ Always check == 0 for equality!</div></div>"

             "<div class='entry'><h3>strncmp(s1, s2, size_t n)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Compare first n characters. Perfect for checking prefixes!</p>"
             "<span class='label'>Example:</span>"
             "<pre>char *req = \"GET /api HTTP/1.1\";\n"
             "if (strncmp(req, \"GET\", 3) == 0) {\n"
             "    printf(\"It's a GET!\\n\");\n"
             "}</pre></div>"

             "<div class='entry'><h3>atoi(const char *str)</h3>"
             "<span class='label'>What it does:</span>"
             "<p>Converts string to integer. \"ASCII to Integer\".</p>"
             "<span class='label'>Example:</span>"
             "<pre>char *port_str = \"8080\";\n"
             "int port = atoi(port_str);  // port = 8080\n"
             "\n"
             "// Parse command line\n"
             "int count = atoi(argv[1]);</pre>"
             "<div class='warn'>⚠️ Returns 0 on error (can't tell if \"0\" or invalid)</div></div>"

             // Network Functions
             "</div><div class='cat'><h2>🌐 Network Functions - The Core</h2>"
             "<p>These power EVERY network program - web servers, chat apps, games, everything!</p>");

    // Continue with detailed network functions...
    strcat(html,
           "<div class='entry'><h3>socket(int domain, int type, int protocol)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Creates a socket - your program's connection to the network. Like installing a phone in your house.</p>"
           "<span class='label'>Parameters explained:</span>"
           "<ul>"
           "<li><code>domain</code>: AF_INET (IPv4), AF_INET6 (IPv6)</li>"
           "<li><code>type</code>: SOCK_STREAM (TCP - reliable) or SOCK_DGRAM (UDP - fast)</li>"
           "<li><code>protocol</code>: Usually 0 (auto-select)</li>"
           "</ul>"
           "<span class='label'>Example:</span>"
           "<pre>// Create TCP socket for IPv4\n"
           "int sock = socket(AF_INET, SOCK_STREAM, 0);\n"
           "if (sock < 0) {\n"
           "    perror(\"socket failed\");\n"
           "    return -1;\n"
           "}\n"
           "printf(\"Socket created: fd = %%d\\n\", sock);</pre>"
           "<span class='label'>What happens:</span>"
           "<ul><li>OS creates socket structure</li>"
           "<li>Returns file descriptor (integer like 3, 4, 5)</li>"
           "<li>You use this fd for all network operations</li></ul>"
           "<div class='tip'>💡 In Unix, everything is a file! Sockets are files.</div></div>"

           "<div class='entry'><h3>bind(int sockfd, struct sockaddr *addr, socklen_t len)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Assigns IP address and port to your socket. Like giving your phone a phone number.</p>"
           "<span class='label'>Why you need it:</span>"
           "<p>Servers need a known address so clients can find them. Web servers bind to port 80/8080.</p>"
           "<span class='label'>Complete example:</span>"
           "<pre>int sock = socket(AF_INET, SOCK_STREAM, 0);\n"
           "\n"
           "struct sockaddr_in addr;\n"
           "memset(&addr, 0, sizeof(addr));\n"
           "\n"
           "addr.sin_family = AF_INET;           // IPv4\n"
           "addr.sin_addr.s_addr = INADDR_ANY;   // All IPs (0.0.0.0)\n"
           "addr.sin_port = htons(8080);         // Port 8080\n"
           "\n"
           "if (bind(sock, (struct sockaddr*)&addr, sizeof(addr)) < 0) {\n"
           "    perror(\"bind failed\");\n"
           "    return -1;\n"
           "}</pre>"
           "<span class='label'>What INADDR_ANY means:</span>"
           "<p>Accept connections on ALL network interfaces (WiFi, Ethernet, loopback). "
           "Clients can connect via any of your IPs.</p>"
           "<span class='label'>What htons() does:</span>"
           "<p>Converts to network byte order (big-endian). Different computers store numbers differently, "
           "network uses one standard. htons = host to network short.</p>"
           "<div class='warn'>⚠️ \"Address in use\" error? Another program is using that port or use SO_REUSEADDR</div></div>"

           "<div class='entry'><h3>listen(int sockfd, int backlog)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Marks socket as passive - ready to accept connections. Says \"I'm ready for clients!\"</p>"
           "<span class='label'>Parameters:</span>"
           "<ul><li>sockfd: Your socket</li>"
           "<li>backlog: Max queue size (5-128). When clients connect faster than you accept, they queue here.</li></ul>"
           "<span class='label'>Example:</span>"
           "<pre>// After socket() and bind()\n"
           "if (listen(sock, 10) < 0) {\n"
           "    perror(\"listen\");\n"
           "    return -1;\n"
           "}\n"
           "printf(\"Listening on port 8080\\n\");</pre>"
           "<div class='tip'>💡 Like turning on your phone's ringer - now ready to receive calls</div></div>"

           "<div class='entry'><h3>accept(int sockfd, struct sockaddr *addr, socklen_t *len)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Accepts incoming client. THIS IS WHERE SERVER WAITS. Blocks (sleeps) until client connects.</p>"
           "<span class='label'>Returns:</span>"
           "<p>NEW socket for this specific client. Original socket stays open for more clients.</p>"
           "<span class='label'>Complete example:</span>"
           "<pre>struct sockaddr_in client_addr;\n"
           "socklen_t len = sizeof(client_addr);\n"
           "\n"
           "printf(\"Waiting for client...\\n\");\n"
           "\n"
           "// BLOCKS HERE until someone connects\n"
           "int client = accept(sock, \n"
           "                   (struct sockaddr*)&client_addr,\n"
           "                   &len);\n"
           "\n"
           "if (client < 0) {\n"
           "    perror(\"accept\");\n"
           "    return -1;\n"
           "}\n"
           "\n"
           "// Get client IP\n"
           "char ip[INET_ADDRSTRLEN];\n"
           "inet_ntop(AF_INET, &client_addr.sin_addr, \n"
           "          ip, INET_ADDRSTRLEN);\n"
           "printf(\"Client connected: %%s\\n\", ip);\n"
           "\n"
           "// Now talk to client\n"
           "recv(client, buffer, size, 0);\n"
           "send(client, response, len, 0);\n"
           "close(client);</pre>"
           "<span class='label'>Key concepts:</span>"
           "<ul><li><b>Blocking:</b> accept() waits until connection</li>"
           "<li><b>Two sockets:</b> Server socket (listening) + client socket (talking)</li>"
           "<li><b>Client info:</b> client_addr tells who connected</li></ul>"
           "<div class='tip'>💡 server_sock = front desk phone, client_sock = direct line to customer</div></div>"

           "<div class='entry'><h3>send(int sockfd, void *buf, size_t len, int flags)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Sends data through socket to other side. How you transmit over network!</p>"
           "<span class='label'>Parameters:</span>"
           "<ul><li>sockfd: Socket to send through</li>"
           "<li>buf: Your data</li><li>len: Bytes to send</li>"
           "<li>flags: Usually 0</li></ul>"
           "<span class='label'>Returns:</span>"
           "<p>Bytes actually sent, or -1 on error. May send less than requested!</p>"
           "<span class='label'>Example:</span>"
           "<pre>const char *msg = \"Hello!\";\n"
           "ssize_t sent = send(client, msg, strlen(msg), 0);\n"
           "if (sent < 0) {\n"
           "    perror(\"send\");\n"
           "}\n"
           "\n"
           "// Send HTTP response\n"
           "&lt;char resp[500];&gt;\\n<br>"
           "&lt;snprintf(resp, sizeof(resp),&gt;\\n<br>"
           "&nbsp;&nbsp;&quot;HTTP/1.1 200 OK\\\\r\\\\n&quot;\\n<br>"
           "&nbsp;&nbsp;&quot;Content-Type: text/html\\\\r\\\\n\\\\r\\\\n&quot;\\n<br>"
           "&nbsp;&nbsp;&quot;&lt;h1&gt;Hello&lt;/h1&gt;&quot;);\\n<br>"
           "&lt;send(client, resp, strlen(resp), 0);&gt;\\n<br>"
           "<span class='label'>Behind the scenes:</span>"
           "<ul><li>Data copied to kernel buffer</li>"
           "<li>Broken into TCP packets</li>"
           "<li>Sent across network</li>"
           "<li>TCP ensures delivery (resends if lost)</li></ul>"
           "<div class='warn'>⚠️ For large data, may need to loop (partial sends)</div></div>"

           "<div class='entry'><h3>recv(int sockfd, void *buf, size_t len, int flags)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Receives data from socket. How you read what was sent!</p>"
           "<span class='label'>Returns:</span>"
           "<ul><li>&gt;0: Bytes received</li>"
           "<li>0: Connection closed</li>"
           "<li>-1: Error</li></ul>"
           "<span class='label'>Example:</span>"
           "<pre>char buffer[4096];\n"
           "\n"
           "// BLOCKS until data arrives\n"
           "ssize_t n = recv(client, buffer, sizeof(buffer)-1, 0);\n"
           "\n"
           "if (n < 0) {\n"
           "    perror(\"recv\");\n"
           "} else if (n == 0) {\n"
           "    printf(\"Client disconnected\\n\");\n"
           "} else {\n"
           "    buffer[n] = '\\0';  // Null-terminate\n"
           "    printf(\"Received: %%s\\n\", buffer);\n"
           "}</pre>"
           "<span class='label'>Reading HTTP request:</span>"
           "<pre>char request[8192];\n"
           "ssize_t n = recv(client, request, sizeof(request)-1, 0);\n"
           "if (n > 0) {\n"
           "    request[n] = '\\0';\n"
           "    if (strncmp(request, \"GET\", 3) == 0) {\n"
           "        // Handle GET\n"
           "    }\n"
           "}</pre>"
           "<div class='warn'>⚠️ recv() blocks until data arrives or timeout</div>"
           "<div class='tip'>💡 Always save room for \\0: use sizeof(buf)-1</div></div>"

           "<div class='entry'><h3>close(int fd)</h3>"
           "<span class='label'>What it does:</span>"
           "<p>Closes file descriptor (socket, file, pipe). For sockets, disconnects connection.</p>"
           "<span class='label'>Why important:</span>"
           "<p>Limited file descriptors (~1024). Must close when done or run out!</p>"
           "<span class='label'>Example:</span>"
           "<pre>// After handling client\n"
           "send(client, response, len, 0);\n"
           "close(client);  // Disconnect\n"
           "\n"
           "// Shutdown server\n"
           "close(server_sock);  // Stop accepting</pre>"
           "<div class='tip'>💡 close() on socket sends TCP FIN packet - graceful shutdown</div></div>");

    // Add constants section
    strcat(html,
           "</div><div class='cat'><h2>📊 Important Constants</h2>"

           "<div class='entry'><h3>AF_INET</h3>"
           "<span class='label'>What it is:</span>"
           "<p>Address Family for IPv4 (regular IP addresses like 192.168.1.1).</p>"
           "<span class='label'>Usage:</span>"
           "<pre>socket(AF_INET, SOCK_STREAM, 0);\n"
           "addr.sin_family = AF_INET;</pre></div>"

           "<div class='entry'><h3>SOCK_STREAM</h3>"
           "<span class='label'>What it is:</span>"
           "<p>TCP socket type - reliable, ordered, connection-oriented.</p>"
           "<span class='label'>What it means:</span>"
           "<ul><li><b>Reliable:</b> Data guaranteed to arrive</li>"
           "<li><b>Ordered:</b> Arrives in send order</li>"
           "<li><b>Connection:</b> Must connect first</li></ul>"
           "<span class='label'>Use for:</span>"
           "<p>Web servers, file transfer, databases, SSH, anything needing reliability.</p></div>"

           "<div class='entry'><h3>INADDR_ANY</h3>"
           "<span class='label'>What it is:</span>"
           "<p>Special IP 0.0.0.0 meaning \"all network interfaces\".</p>"
           "<span class='label'>When to use:</span>"
           "<p>For servers - accept connections on ANY of your computer's IPs.</p>"
           "<span class='label'>Example scenario:</span>"
           "<p>Your computer has 127.0.0.1 (localhost), 192.168.1.100 (WiFi), 10.0.0.50 (VPN). "
           "INADDR_ANY means clients can connect via ANY of these!</p>"
           "<pre>addr.sin_addr.s_addr = INADDR_ANY;</pre></div>"

           "<div class='entry'><h3>INET_ADDRSTRLEN</h3>"
           "<span class='label'>What it is:</span>"
           "<p>Buffer size for IPv4 string. Value: 16 bytes.</p>"
           "<span class='label'>Why 16:</span>"
           "<p>Longest IPv4: \"255.255.255.255\" = 15 chars + \\0 = 16</p>"
           "<span class='label'>Example:</span>"
           "<pre>char ip[INET_ADDRSTRLEN];\n"
           "inet_ntop(AF_INET, &addr.sin_addr, ip, INET_ADDRSTRLEN);</pre></div>"

           "<div class='entry'><h3>NULL</h3>"
           "<span class='label'>What it is:</span>"
           "<p>Pointer value meaning \"points to nothing\". Usually 0.</p>"
           "<span class='label'>When to use:</span>"
           "<ul><li>Initialize: <code>int *p = NULL;</code></li>"
           "<li>Check valid: <code>if (p != NULL)</code></li>"
           "<li>After free: <code>free(p); p = NULL;</code></li></ul>"
           "<div class='warn'>⚠️ Dereferencing NULL (*NULL) = segfault (crash)!</div></div>"

           "</div><div style='margin:40px 0;padding:20px;background:#1a1a1a;border-left:5px solid #00ff00;'>"
           "<a href='/'>← Home</a> | <a href='/how-it-works'>How servers work</a> | <a href='/info'>Network concepts</a>"
           "</div>"

           "<script>"
           "const s=document.getElementById('s'),es=document.querySelectorAll('.entry'),c=document.getElementById('c');"
           "function u(){const v=Array.from(es).filter(e=>e.style.display!=='none').length;"
           "c.textContent='Showing '+v+' of '+es.length+' functions';}"
           "s.oninput=function(){const q=this.value.toLowerCase();"
           "es.forEach(e=>{e.style.display=(q===''||e.textContent.toLowerCase().includes(q))?'block':'none';});u();};"
           "u();</script></body></html>");

    response->status_code = 200;
    strcpy(response->content_type, "text/html; charset=utf-8");
    response->body = html;
    response->body_length = strlen(html);
}